# Generated by Django 6.0.4 on 2026-05-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropoffcenter',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='WGS84 latitude for map and nearby search', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='dropoffcenter',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='WGS84 longitude for map and nearby search', max_digits=9, null=True),
        ),
    ]
