# Generated by Django 6.0 on 2025-12-10 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('drop_off_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dropoffcenter')),
            ],
        ),
        migrations.CreateModel(
            name='RecyclableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('paper', 'Paper'), ('plastic', 'Plastic')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in KG', max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='recyclables/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('collected', 'Collected')], default='pending', max_length=20)),
                ('points_earned', models.IntegerField(default=0)),
                ('amount_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('drop_off_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.dropoffcenter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recyclables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
